---
apiVersion: v1
kind: Service
metadata:
  name: traefikee-api
  namespace: '{{ meta.namespace }}'
  labels:
    app: {{ appName }}
spec:
  ports:
    - port: 8080
      name: api
  selector:
    app: {{ appName }}
    component: control-nodes
    subcomponent: control-node
