---
apiVersion: v1
kind: Service
metadata:
  name: traefikee-lb
  namespace: '{{ meta.namespace }}'
  labels:
    app: {{ clustername }}
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
  selector:
    component: data-nodes
    app: {{ clustername }}
