---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefikee
  namespace: '{{ meta.namespace }}'
  labels:
    app: {{ appName }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefikee-role
  namespace: '{{ meta.namespace }}'
  labels:
    app: {{ appName }}
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "extensions"
    resources:
      - ingresses/status
    verbs:
      - update
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - update
      - delete
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefikee
  namespace: '{{ meta.namespace }}'
  labels:
    app: {{ appName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefikee-role
subjects:
- kind: ServiceAccount
  name: traefikee
  namespace: '{{ meta.namespace }}'
