kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: traefikee-operator
  # namespace: traefikee
subjects:
- kind: ServiceAccount
  name: traefikee-operator
  namespace: traefikee
roleRef:
  kind: ClusterRole
  name: traefikee-operator
  apiGroup: rbac.authorization.k8s.io
